# Generated by Django 4.2.2 on 2023-07-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.IntegerField(),
        ),
    ]
